
services:
  - type: web
    name: piishield-assignment
    env: python
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT